default_config:


automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize:
    climate.smart_thermostat:
      scan_interval: 10  # Updates every 10 seconds

logger:
  # default: info
  logs:
    # custom_components.smart_thermostat: debug
    # custom_components.smart_thermostat.climate: debug
    custom_components.smartir: critical
    # homeassistant.components.climate: debug
    # homeassistant.core: info
    # custom_components.mock_hvac: debug
    # custom_components.mock_hvac.climate: debug
  filters:
    ignore_custom_components: []


smartir:
climate:
  - platform: smartir
    name: "Primary HP"
    unique_id: primary_hp
    device_code: 2161
    controller_data: remote.broadlink_primary
    temperature_sensor: sensor.broadlink_primary_temperature
    humidity_sensor: sensor.broadlink_primary_humidity
  - platform:smartir
    name: "Basement HP"
    unique_id: basement_hp
    device_code: 2161
    controller_data: remote.broadlink_basement
    temperature_sensor: sensor.basement_temperature
    humidity_sensor: sensor.basement_humidity
  - platform: smartir
    name: "bedroom HP"
    unique_id: bedroom_hp
    device_code: 2161
    controller_data: remote.broadlink_bedroom
    temperature_sensor: sensor.bedroom_temperature
  - platform: smart_thermostat
    name: "Smart Furnace"
    temperature_sensors:
      - sensor.broadlink_bedroom_temperature
      - sensor.thermostat_current_temperature
      - sensor.broadlink_primary_temperature
    hvac_entity: climate.thermostat
    heat_pump_entity: climate.primary_hp
    target_temp: 21.5
    min_temp: 19.0
    max_temp: 25
    tolerance: 0.5
    minimum_on_time: 5
    maximum_on_time: 15
    off_time: 20
    heat_pump_min_temp: -25
    heat_pump_max_temp: 15

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/mushroom-cards/mushroom.js 